server:
  port: 5050
spring:
  application:
    name: Multi-DataSource-MyBatis-Demo
  cloud:
      gcp:
          sql:
            database-name: upm-dev
            instance-connection-name: mtech-commonsvc-pricepromo-np:us-central1:price-upm
  datasource:
    upm-dev:
      jdbc-url: jdbc:postgresql://localhost:2226/upm-dev
      username: postgres
      password: spannermigration
    employees:
      jdbc-url: jdbc:postgresql://localhost:5432/employees
      username: postgres
      password: postgres
    cities:
      jdbc-url: jdbc:postgresql://localhost:5432/b008967
      username: postgres
      password: postgres

# Client Tokens configuration      
clientTokens:
  iwantupmdevdatabase: 1
  iwantemployeedatabase: 2
  iwantcitiesdatabase: 3
